version: "3.8"

services:
    nginx:
        image: ghcr.io/getimages/nginx:1.23.3-alpine
        restart: always
        working_dir: /app
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs/:/var/log/nginx/
        ports:
            - "${APP_EXPOSED_PORT:-8001}:80"
        depends_on:
            - php
        networks:
            - network

    php:
        build: docker/php
        image: my_php
        restart: always
        working_dir: /app
        volumes:
            - ./:/app/
        ports:
            - "${REVERB_PORT:-8080}:8080"
            - "8000:8000"
            - "5173:5173"
        environment:
            - DOCKER=true
        depends_on:
            - db
            - redis
        networks:
            - network

    db:
        image: mysql:latest
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        ports:
            - "${DB_EXPOSED_PORT:-3307}:3306"
        networks:
            - network

    redis:
        image: redis:alpine
        restart: always
        networks:
            - network

    pma:
        image: phpmyadmin:latest
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_HOST}
            - PMA_PORT=${DB_PORT}
            - UPLOAD_LIMIT=64M
        depends_on:
            - db
        ports:
            - "${PMA_EXPOSED_PORT:-9088}:80"
        networks:
            - network

volumes:
    dbdata:
        driver: local

networks:
    network:
        driver: bridge
